service: school-qa-recommender

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    ${file(serverless/iam_role.yml):iamRoleStatements}
  environment:
    STAGE_NAME: "${self:custom.stageName}"
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}

plugins:
  - serverless-plugin-split-stacks
  - serverless-python-requirements

package:
  execute:
    - node_modules/*
    - authentication/**
    - dashboard/**
    - tests/**

custom:
  stageName: "${opt:stage, self:provider.stage}"
  resourcePrefix: "${self:custom.stageName}-qa" 
  lambdaHandlerPrefix: "app/interfaces/"
  splitStacks:
    perFunction: false
    perType: true
    perGroupFunction: true
    nestedStackCount: 50


functions:
  LambdaApiCreateQuestion:
    handler: ${self:custom.lambdaHandlerPrefix}api/question.create_question_handler
    name: ${self:custom.resourcePrefix}-create-question
    events:
      - http:
          path: admin/question
          method: post
          cors: true
          authorizer: aws_iam
    tags:
      TYPE: API
      SERVICE: Question

  LambdaApiGetQuestionList:
    handler: ${self:custom.lambdaHandlerPrefix}api/question.get_question_list_handler
    name: ${self:custom.resourcePrefix}-get-question-list
    events:
      - http:
          path: admin/question
          method: get
          cors: true
          authorizer: aws_iam
    tags:
      TYPE: API
      SERVICE: Question

  LambdaApiFindQuestion:
    handler: ${self:custom.lambdaHandlerPrefix}api/question.find_question_handler
    name: ${self:custom.resourcePrefix}-find-question
    events:
      - http:
          path: admin/question/{question_id}
          method: get
          cors: true
          authorizer: aws_iam
    tags:
      TYPE: API
      SERVICE: Question

  LambdaApiUpdateQuestion:
    handler: ${self:custom.lambdaHandlerPrefix}api/question.update_question_handler
    name: ${self:custom.resourcePrefix}-update-question
    events:
      - http:
          path: admin/question/{question_id}
          method: put
          cors: true
          authorizer: aws_iam
    tags:
      TYPE: API
      SERVICE: Question

  LambdaApiCreateClassRoom:
    handler: ${self:custom.lambdaHandlerPrefix}api/class_room.create_class_room_handler
    name: ${self:custom.resourcePrefix}-create-class-room
    events:
      - http:
          path: admin/class_room
          method: post
          cors: true
          authorizer: aws_iam
    tags:
      TYPE: API
      SERVICE: ClassRoom

resources:
  - ${file(serverless/resources/outputs.yml)}
  - ${file(serverless/resources/dynamodb.yml)}
