Resources:
  ToiToyQuestionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-Question"
      AttributeDefinitions:
        -
          AttributeName: "question_id"
          AttributeType: "N"
        -
          AttributeName: "register_user_id"
          AttributeType: "S"
        -
          AttributeName: "register_date"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "question_id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        -
          IndexName: "RegisterUserId-Index"
          KeySchema:
            -
              AttributeName: "register_user_id"
              KeyType: "HASH"
            -
              AttributeName: "register_date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"

  ToiToySequensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-Sequenses"
      AttributeDefinitions:
        -
          AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "name"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  ToiToyClassroomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-Classroom"
      AttributeDefinitions:
        -
          AttributeName: "classroom_id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "classroom_id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  ToiToyClassmateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-Classmate"
      AttributeDefinitions:
        -
          AttributeName: "classroom_id"
          AttributeType: "N"
        -
          AttributeName: "user_id"
          AttributeType: "S"
        -
          AttributeName: "join_status"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "classroom_id"
          KeyType: "HASH"
        -
          AttributeName: "user_id"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        -
          IndexName: "UserId-Index"
          KeySchema:
            -
              AttributeName: "user_id"
              KeyType: "HASH"
            -
              AttributeName: "join_status"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"

  ToiToyWorkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-Work"
      AttributeDefinitions:
        -
          AttributeName: "work_id"
          AttributeType: "N"
        -
          AttributeName: "classroom_id"
          AttributeType: "N"
        -
          AttributeName: "register_date"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "work_id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        -
          IndexName: "Classroom-Index"
          KeySchema:
            -
              AttributeName: "classroom_id"
              KeyType: "HASH"
            -
              AttributeName: "register_date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
  ToiToyWorkCommentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-WorkComment"
      AttributeDefinitions:
        -
          AttributeName: "comment_id"
          AttributeType: "N"
        -
          AttributeName: "work_id"
          AttributeType: "N"
        -
          AttributeName: "register_date"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "comment_id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        -
          IndexName: "WorkId-Index"
          KeySchema:
            -
              AttributeName: "work_id"
              KeyType: "HASH"
            -
              AttributeName: "register_date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"

  ToiToyClassroomInviteTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-ClassmateInvite"
      AttributeDefinitions:
        -
          AttributeName: "classroom_id"
          AttributeType: "N"
        -
          AttributeName: "invite_key"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "classroom_id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        -
          IndexName: "InviteKey-Index"
          KeySchema:
            -
              AttributeName: "invite_key"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
