Resources:
  ToiToyQuestionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-Question"
      AttributeDefinitions:
        -
          AttributeName: "question_id"
          AttributeType: "N"
        -
          AttributeName: "register_user_id"
          AttributeType: "S"
        -
          AttributeName: "register_date"
          AttributeType: "S"
        -
          AttributeName: "subject_type"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "question_id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        -
          IndexName: "RegisterUser-Index"
          KeySchema:
            -
              AttributeName: "register_user_id"
              KeyType: "HASH"
            -
              AttributeName: "register_date"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "question_id"
              - "estimated_time"
              - "register_user_name"
              - "register_date"
              - "subject_type"
              - "sort_tag_list"
              - "question_sentence"
              - "question_type"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        -
          IndexName: "SubjectType-Index"
          KeySchema:
            -
              AttributeName: "subject_type"
              KeyType: "HASH"
            -
              AttributeName: "register_date"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "question_id"
              - "register_user_id"
              - "register_user_name"
              - "estimated_time"
              - "sort_tag_list"
              - "question_sentence"
              - "question_type"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

  ToiToySequensesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-Sequenses"
      AttributeDefinitions:
        -
          AttributeName: "name"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "name"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  ToiToyClassroomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-Classroom"
      AttributeDefinitions:
        -
          AttributeName: "classroom_id"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "classroom_id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  ToiToyClassmateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-Classmate"
      AttributeDefinitions:
        -
          AttributeName: "classroom_id"
          AttributeType: "N"
        -
          AttributeName: "user_id"
          AttributeType: "S"
        -
          AttributeName: "join_status"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "classroom_id"
          KeyType: "HASH"
        -
          AttributeName: "user_id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        -
          IndexName: "UserId-Index"
          KeySchema:
            -
              AttributeName: "user_id"
              KeyType: "HASH"
            -
              AttributeName: "join_status"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

  ToiToyWorkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-Work"
      AttributeDefinitions:
        -
          AttributeName: "work_id"
          AttributeType: "N"
        -
          AttributeName: "classroom_id"
          AttributeType: "N"
        -
          AttributeName: "register_date"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "work_id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        -
          IndexName: "Classroom-Index"
          KeySchema:
            -
              AttributeName: "classroom_id"
              KeyType: "HASH"
            -
              AttributeName: "register_date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
  ToiToyWorkCommentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "${self:custom.resourcePrefix}-WorkComment"
      AttributeDefinitions:
        -
          AttributeName: "comment_id"
          AttributeType: "N"
        -
          AttributeName: "work_id"
          AttributeType: "N"
        -
          AttributeName: "register_date"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "comment_id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        -
          IndexName: "WorkId-Index"
          KeySchema:
            -
              AttributeName: "work_id"
              KeyType: "HASH"
            -
              AttributeName: "register_date"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
