Resources:
  ToiToyPrivateImageStorage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.stageName}-toi-toy-private-image-storage
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedHeaders:
              - '*'
